
networks:
  default:
    driver: bridge

services:

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
    depends_on:
      - influxdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: unless-stopped
    user: "0"
    ports:
      - "8086:8086"
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/backup:/var/lib/influxdb/backup

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log

  # ------------------------------------------------------
  # Node-RED NÃO SERÁ UTILIZADO
  # Mantido comentado para histórico técnico do projeto
  # ------------------------------------------------------
  # nodered:
  #   container_name: nodered
  #   image: nodered/node-red:latest
  #   restart: unless-stopped
  #   ports:
  #     - "1880:1880"
  #   environment:
  #     - TZ=${TZ:-America/Sao_Paulo}
  #   volumes:
  #     - ./volumes/nodered/data:/data

  python:
    container_name: python-iot
    build: ./services/python
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - PYTHONUNBUFFERED=1
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_DB=monitoramento_ambiental
    volumes:
      - ./services/python/app:/app
    depends_on:
      - mosquitto
      - influxdb

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

